version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and lock files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Open pull requests for updates on the develop branch
    target-branch: "develop"
    # Limit number of open PRs
    open-pull-requests-limit: 10
    
  # Enable version updates for npm in ai2-core-app
  - package-ecosystem: "npm"
    directory: "/ai2-core-app"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
