app = 'ai2-analytics'
primary_region = 'syd'

[env]
  NODE_ENV = "production"
  WAZUH_HOST = "ai2-wazuh.internal"
  WAZUH_SYSLOG_PORT = "514"
  WAZUH_MANAGER_URL = "https://ai2-wazuh.fly.dev"
  APP_NAME = "ai2-analytics"

[build]

[http_service]
  internal_port = 3004
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[deploy]
  # release_command = ""
